In [ ]:
import pandas as pd

data={
        'A':[1,2,3,4,None],
        'B':[1,2,3,None,5]
}

print(data)
df=pd.DataFrame(data)

df.head()
#drop not available values none values
df_dropna=df.dropna()
#fill the values with 
df_fillna=df.fillna(0)

print("Dataframe :\n",df)
print("Dataframe after dropping missing values:\n",df_dropna)
print("Dataframe after filling the specific value:\n",df_fillna)


{'A': [1, 2, 3, 4, None], 'B': [1, 2, 3, None, 5]}
Dataframe :
      A    B
0  1.0  1.0
1  2.0  2.0
2  3.0  3.0
3  4.0  NaN
4  NaN  5.0
Dataframe after dropping missing values:
      A    B
0  1.0  1.0
1  2.0  2.0
2  3.0  3.0
Dataframe after filling the specific value:
      A    B
0  1.0  1.0
1  2.0  2.0
2  3.0  3.0
3  4.0  0.0
4  0.0  5.0


In [26]:
import numpy as np

a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1=np.array([1,2,3])
print(a1)
print(a2)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
a1.shape
a1=a1/10.0/10.5
a1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])